apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: apache
spec:
  replicas: 3
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
      - name: php-apache
        image: httpd
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        volumeMounts:
        - name: testshare
          mountPath: /var/www/html/
      volumes:
        - name: testshare
          hostPath:
            path: /data
